language: java
sudo: false
install: true
dist: trusty

addons:
  sonarcloud:
    organization: "felberto-github"
    token:
      secure: SONAR_TOKEN_BACKEND

jobs:
  include:
  - stage: build
    script:
    - mvn clean package -DskipTests -Pprod
  - stage: sonar
    script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar