language: java
jdk:
- openjdk11

dist: trusty

jobs:
  include:
  - stage: sonar
      script:
      - mvn clean verify -Psonar -Dsonar.login=$SONAR_LOGIN_TOKEN
  - stage: build
      script:
      - mvn clean install -DskipTests -Pprod