language: java
jdk:
- openjdk11

dist: trusty

addons:
  sonarcloud:
    organization: "felberto-github"
    token:
      secure: $SONAR_TOKEN

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
- mvn clean install -DskipTests -Pprod