language: java
jdk:
- openjdk11

dist: trusty

jobs:
  include:
  - stage: sonar
    script:
    - mvn clean verify -Psonar -Dsonar.login=$SONAR_LOGIN_TOKEN -Dsonar.branch.name=$TRAVIS_BRANCH
  - stage: build
    script:
    - mvn clean install -DskipTests -Pprod
  - stage: deploy
    if: branch = master
    script:
    - HEROKU_API_KEY="$HEROKU_TOKEN" mvn clean heroku:deploy-war