language: java
jdk:
- openjdk11

dist: trusty

addons:
  sonarcloud:
    organization: "felberto-github"
    token:
      secure: $SONAR_TOKEN

script:
- mvn clean verify-P sonar
- mvn clean install -DskipTests -Pprod