language: java
jdk:
- openjdk11

dist: trusty

jobs:
  include:
  - stage: sonar
    script:
    - mvn clean verify -Psonar -Dsonar.login=$SONAR_LOGIN_TOKEN -Dsonar.branch.name=$TRAVIS_BRANCH
  - stage: build
    script:
      - mvn clean install -DskipTests -Pprod
  - stage: deploy
    script:
    - HEROKU_API_KEY="88b73111-8450-4f82-950b-b643f0456839" mvn clean heroku:deploy