language: java
sudo: false
install: true
dist: trusty

addons:
  sonarcloud:
    organization: "felberto-github"
    token:
      secure: SONAR_TOKEN_BACKEND

jobs:
  include:
  - stage: build
    script:
    - mvn clean package -DskipTests -Pprod
  - stage: sonar-backend
    script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.login=$SONAR_TOKEN_BACKEND