language: java

dist: trusty

jobs:
  include:
  - stage: sonar
    script:
    - mvn clean verify -Psonar -Dsonar.login=$SONAR_LOGIN_TOKEN -Dsonar.branch.name=$TRAVIS_BRANCH
  - stage: build
    script:
    - mvn clean package -DskipTests -Pprod
  - stage: deploy
    if: branch = master
    script:
    - HEROKU_API_KEY="$HEROKU_TOKEN" sudo mvn clean heroku:deploy -Dserver.port=8080